config/routes.rb
module UserConstraint
  def current_user(request)
    User.find_by_id(request.session[:user_id])
  end
end

class DispatcherRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    p user.present? && user.role == 'dispatcher'
    user.present? && user.role == 'dispatcher'
  end
end

class DriverRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    user.present? && user.role == 'driver'
  end
end


Rails.application.routes.draw do
  constraints(DispatcherRequiredConstraint.new) do
    resources :orders, only: [:index, :edit, :update, :destroy] do
      patch :shift, on: :member
      post :split, on: :member
      post :import, on: :collection
    end

    resources :loads, only: [:create] do
      patch :complete, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :dispatcher
      delete :destroy_all
    end

    root to: 'dashboards#dispatcher', as: nil
  end

  constraints(DriverRequiredConstraint.new) do
    resources :loads, only: [:index] do
      get :export, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :driver
    end

    root to: 'dashboards#driver', as: nil
  end

  resources :sessions

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  root to: 'dashboards#index'
end

app/models/load.rb
class Load < ActiveRecord::Base
  MAX_VOLUME = 1400.0
  BASE_DATE =

  has_many :orders
  enum shift: { morning: 1, noon: 2, evening: 3 }

  validates :delivery_date, presence: true
  validates :shift, uniqueness: { scope: :delivery_date }

  validate :check_orders_delivery_date
  validate :check_orders_shift
  validate :check_reverse_orders_position

  scope :by_date, -> (date) { where(delivery_date: date) }

  def self.for_truck_and_date(truck_number, date)
    shifts = ((date - Date.parse('2014-01-01')).to_i + truck_number).odd? ? [1, 3] : [2]
    self.where(delivery_date: date, shift: shifts)
  end

  private

  def check_orders_delivery_date
    unless orders.pluck(:delivery_date).compact.all? { |order_date| order_date == delivery_date }
      errors.add :orders, :invalid_delivery_date
    end
  end

  def check_orders_shift
    unless orders.map(&:shift).all? { |order_shift| order_shift == 'not_specified' || order_shift == shift }
      errors.add :orders, :invalid_shift
    end
  end

  def check_reverse_orders_position
    first_reverse_order = orders.where(reverse: true).order(:position).first
    return true unless first_reverse_order
    after_orders = orders.where('position > ?', first_reverse_order.position)
    if after_orders.where(reverse: false).any?
      errors.add :orders, :invalid_reverse_positions
    end
  end

end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :parse_date
  before_action :find_load, only: [:complete]

  def index
    @loads = Load.for_truck_and_date(current_user.truck_number, @date).order(:shift).includes(orders: [:origin, :destination]).where(completed: true)
  end

  def create
    @loads = ['morning', 'noon', 'evening'].map do |shift|
       Load.new(delivery_date: @date, shift: shift)
    end
    flash[:danger] = @loads.flat_map {|l| l.errors.full_messages}.uniq unless @loads.map(&:save).all?
    redirect_to orders_url(date: @date)
  end

  def complete
    unless @load.update(completed: true)
      flash[:danger] = @load.errors.full_messages
     end
    redirect_to orders_url(date: @date)
  end

  def export
    @load = Load.where(completed: true).find(params[:id])
  end

  private

  def parse_date
    @date = Date.parse(params[:date]) rescue nil
  end

  def find_load
    @load = Load.find(params[:id])
  end
end

app/views/loads/_load.html.slim
h3 = "#{t('.load')} #{load.shift}"

.volume
  = "#{Load.human_attribute_name(:volume)} : #{load.volume}; "
  = "#{Load.human_attribute_name(:reverse_volume)} : #{load.reverse_volume}"

.quantity
  = "#{Load.human_attribute_name(:quantity)} : #{load.quantity}; "
  = "#{Load.human_attribute_name(:reverse_quantity)} : #{load.reverse_quantity}"

table.table.table-bordered
  - unless load.orders.empty?
    = render 'shared/orders_table_header'
    = render load.orders.order(:position)

- unless load.completed?
  = link_to t('.complete'), complete_load_path(load, date: @date), data: { confirm: 'Are you sure?' }, method: :patch, class: "btn btn-success"
- else
  h4 = "#{t('.completed')}"

- if current_user.role == 'driver'
  = link_to t('.export'), export_load_path(load, date: @date, format: :txt), target: '_blank'

app/views/loads/export.text.slim
| Delivery Date: 
= @load.delivery_date
= "\n"
| Delivery Shift: 
= @load.shift
= "\n"
| Load Summary Volume: 
= @load.volume
= "\n"
| Load Summary Quantity: 
= @load.quantity
= "\n"
| Load Reverse Volume: 
= @load.reverse_volume
= "\n"
| Load Reverse Quantity: 
= @load.reverse_quantity
= "\n"

= render @load.orders.order(:position)

app/views/loads/index.html.slim
h2 = t('.loads_for_date', date: @date)
= render @loads