config/routes.rb
module UserConstraint
  def current_user(request)
    User.find_by_id(request.session[:user_id])
  end
end

class DispatcherRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    p user.present? && user.role == 'dispatcher'
    user.present? && user.role == 'dispatcher'
  end
end

class DriverRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    user.present? && user.role == 'driver'
  end
end


Rails.application.routes.draw do
  constraints(DispatcherRequiredConstraint.new) do
    resources :orders, only: [:index, :edit, :update, :destroy] do
      patch :shift, on: :member
      post :split, on: :member
      post :import, on: :collection
    end

    resources :loads, only: [:create] do
      patch :complete, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :dispatcher
      delete :destroy_all
    end

    root to: 'dashboards#dispatcher', as: nil
  end

  constraints(DriverRequiredConstraint.new) do
    resources :loads, only: [:index] do
      get :export, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :driver
    end

    root to: 'dashboards#driver', as: nil
  end

  resources :sessions

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  root to: 'dashboards#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :origin, class_name: 'Location'
  belongs_to :destination, class_name: 'Location'
  belongs_to :load
  acts_as_list scope: :load
  counter_culture :load,
    column_name: Proc.new {|order| order.reverse? ? :reverse_volume : :volume },
    delta_column: :volume

  counter_culture :load,
    column_name: Proc.new {|order| order.reverse? ? :reverse_quantity : :quantity },
    delta_column: :quantity

  validates :origin, :destination, presence: true
  validate :check_difference_of_locations

  validates :number, :delivery_date, presence: true, if: :load

  validate :check_load_delivery_date, if: :load
  validate :check_load_shift, if: :load
  validate :check_load_volume, if: :load
  before_destroy :check_load

  enum shift: { not_specified: 0, morning: 1, noon: 2, evening: 3 }

  scope :shifted, -> { where.not(shift: 0) }
  scope :by_date, -> (date) { where(delivery_date: date) }

  accepts_nested_attributes_for :origin
  accepts_nested_attributes_for :destination

  private

  def check_difference_of_locations
    if origin == destination
      errors.add :destination, :same
    end
  end

  def check_load_delivery_date
    if delivery_date && delivery_date != load.delivery_date
      errors.add :load, :invalid_delivery_date
    end
  end

  def check_load_shift
    unless shift == 'not_specified' || shift == load.shift
      errors.add :load, :invalid_shift
    end
  end

  def check_load_volume
    if (reverse? ? volume + load.reverse_volume : volume + load.volume) > Load::MAX_VOLUME
      errors.add :load, :max_volume_exceeded
    end
  end

  def check_load
    !load
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :parse_date
  before_action :find_order, only: [:show, :edit, :update, :shift, :split, :destroy]

  def index
    @loads = Load.by_date(@date).order(:shift).includes(orders: [:origin, :destination])
    @loads_present = !@loads.empty?
    orders = Order.where(load: nil).by_date(@date).includes(:origin, :destination)
    @shifted_orders = orders.shifted.order(:shift, volume: :desc)
    @not_shifted_orders = orders.not_specified.order(volume: :desc)
  end

  def edit
  end

  def update
    @order.attributes = order_params
    if @order.load && @order.load.completed?
      flash[:danger] = t('update_order_in_completed_load')
    else
      unless @order.save
        flash[:danger] = @order.errors.full_messages
      end
    end
    redirect_to orders_url(date: @order.reload.delivery_date)
  end

  def shift
    if params[:reverse]
      @order.move_higher
    else
      @order.move_lower
    end
    redirect_to orders_url(date: @date)
  end

  def split
    new_volume = params[:new_volume].to_f
    new_quantity = params[:new_quantity].to_i

    flash.now[:danger] ||= []
    flash.now[:danger] << I18n.t('invalid_new_volume') unless new_volume > 0 && new_volume < @order.volume
    flash.now[:danger] << I18n.t('invalid_new_quantity') unless new_quantity > 0 && new_quantity < @order.quantity

    if flash.now[:danger].empty?
      @new_order = Order.new(@order.attributes.merge(id: nil, volume: @order.volume - new_volume, quantity: @order.quantity - new_quantity))
      Order.transaction do
        @order.update!(volume: new_volume, quantity: new_quantity)
        @new_order.save!
      end
      redirect_to orders_url(date: @order.delivery_date)
    else
      render :edit
    end
  rescue Exception => e
    flash.now[:danger] = e.message
    render :edit
  end

  def import
    messages = OrderParser.perform(params[:file], strategy: params[:strategy])
    unless messages[:warnings].empty?
      flash[:warning] = messages[:warnings]
      flash[:warning] << I18n.t('warnings_in_csv')
    end
    if messages[:errors].empty?
      flash[:success] = I18n.t('success_import')
    else
      flash[:danger] = messages[:errors]
      flash[:danger] << I18n.t('errors_in_csv')
    end
  rescue Exception => e
    flash[:danger] = [I18n.t('error_import_file')]
    flash[:danger] << e.message
  ensure
    redirect_to dispatcher_url
  end

  def destroy
    flash[:danger] = I18n.t('cannot_destroy_order_in_load') unless @order.destroy
    redirect_to orders_url(date: @order.delivery_date)
  end

  private

  def parse_date
    @date = Date.parse(params[:date]) rescue nil
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:load_id, :delivery_date, :shift, :number, :phone)
  end

end

app/views/orders/_order.html.slim
- origin = order.origin
- destination = order.destination
- load = order.load
- readonly = load && load.completed?
tr
  td
    - if load
      = order.position
  td
    - if @loads_present && !readonly
      = form_for order, method: :patch do |f|
        = hidden_field_tag :date, @date
        = f.select :load_id, @loads.map {|l| [l.shift, l.id]}, include_blank: true
        = f.submit t('.load')
    - else
      = load.try(:shift)

  td = order.shift
  td = origin.info
  td = destination.info
  td = order.phone
  td = order.id
  td = order.number
  td = order.volume
  td = order.quantity
  td
    - if !readonly
      - if load 
        = link_to t('.up'), shift_order_path(order, date: @date, reverse: true), method: :patch
        br
        = link_to t('.down'), shift_order_path(order, date: @date), method: :patch
      - else
        = link_to t('.edit'), edit_order_path(order)
      

app/views/orders/_order.text.slim
- origin = order.origin
- destination = order.destination
- load = order.load
= "\nCheckPoint # "
= order.position
= "\n"
- if order.reverse?
  = "Reverse order\n"
  = origin.info
- else
  = destination.info
= "\nPhone : "
= order.phone
= "\nNumber : "
= order.number
= "\nUID of order : "
= order.id
= "\nVolume : "
= order.volume
= "\nQuanity : "
= order.quantity
= "\n"

app/views/orders/edit.html.slim
h1 = t('.header')

.origin
  = @order.origin.info
.destination
  = @order.destination.info

.number
  = t('.number')
  br
  = @order.number

.volume
  = t('.volume')
  br
  = @order.volume

.quantity
  = t('quantity')
  br
  = @order.quantity

= form_for @order do |f|
  = f.date_select :delivery_date
  = f.select :shift, Order.shifts.keys
  = f.label :phone
  = f.text_field :phone
  = f.label :number
  = f.text_field :number
  = f.submit

h4 = t('.split_order')
= form_tag split_order_path(@order) do
  = label_tag :new_volume
  = text_field_tag :new_volume
  = label_tag :new_quantity
  = text_field_tag :new_quantity
  = submit_tag t('.split')

h4 = t('.destroy_bad_order')
= link_to t('destroy'), @order, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure to destroy order?' }

app/views/orders/index.html.slim
- if @loads.empty?
  - if @date
    h2 = t('.no_loads', date: @date)
    = form_tag loads_path do
      = hidden_field_tag :date, @date
      = submit_tag t('.create_loads')
- else
  h2 = t('.loads_for_date', date: @date)
  = render @loads

h2 = t('.unloaded_orders')

table.table.table-bordered
  - unless @shifted_orders.empty? && @not_shifted_orders.empty?
    = render 'shared/orders_table_header'
    = render @shifted_orders
    = render @not_shifted_orders
  - else
    h3 = t('.no_orders_for_date')