config/routes.rb
module UserConstraint
  def current_user(request)
    User.find_by_id(request.session[:user_id])
  end
end

class DispatcherRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    p user.present? && user.role == 'dispatcher'
    user.present? && user.role == 'dispatcher'
  end
end

class DriverRequiredConstraint
  include UserConstraint

  def matches?(request)
    user = current_user(request)
    user.present? && user.role == 'driver'
  end
end


Rails.application.routes.draw do
  constraints(DispatcherRequiredConstraint.new) do
    resources :orders, only: [:index, :edit, :update, :destroy] do
      patch :shift, on: :member
      post :split, on: :member
      post :import, on: :collection
    end

    resources :loads, only: [:create] do
      patch :complete, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :dispatcher
      delete :destroy_all
    end

    root to: 'dashboards#dispatcher', as: nil
  end

  constraints(DriverRequiredConstraint.new) do
    resources :loads, only: [:index] do
      get :export, on: :member
    end

    scope :dashboards, controller: :dashboards do
      get :driver
    end

    root to: 'dashboards#driver', as: nil
  end

  resources :sessions

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  root to: 'dashboards#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    if current_user
      if current_user.role == 'dispatcher'
        redirect_to dispatcher_url
      elsif current_user.role == 'driver'
        redirect_to driver_url
      end
    else
      redirect_to login_url
    end
  end

  def dispatcher
    @dates = Order.order(:delivery_date).select(:delivery_date).distinct.pluck(:delivery_date)
    @completed_dates = Load.where(completed: true).group(:delivery_date).having('COUNT(*) = 3').pluck(:delivery_date)
    @uncompleted_dates = @dates - @completed_dates
  end

  def driver
    @dates = Load.where(completed: true).order(:delivery_date).select(:delivery_date).distinct.pluck(:delivery_date)
  end

  def destroy_all
    Order.delete_all
    Load.delete_all
    Location.delete_all
    redirect_to dispatcher_url
  end

end

app/views/dashboards/dispatcher.html.slim
- unless @dates.empty?
  h2 = t('.orders dates')
- unless @completed_dates.empty?
  h3 = t('.completed_dates')
  ul
    - @completed_dates.each do |date|
      li
        = link_to "#{date}", orders_path(date: date)
- unless @uncompleted_dates.empty?
  h3 = t('.uncompleted_dates')
  ul
    - @uncompleted_dates.each do |date|
      li
        = link_to "#{date || 'Date not specified'}", orders_path(date: date)

h2 = t('.import new orders')
= form_tag import_orders_path, multipart: true do
  = file_field_tag :file, required: true
  = submit_tag 'Import'

h2 = t('.import orders with update strategy')
= form_tag import_orders_path, multipart: true do
  = hidden_field_tag :strategy, 'update'
  = file_field_tag :file, required: true
  = submit_tag 'Import only new'

h2 Clean orders and loads for testing purpose
= link_to 'Destroy All', destroy_all_path, method: :delete, data: { confirm: 'Are you sure to delete all orders and loads?' }, class: 'btn btn-danger'

app/views/dashboards/driver.html.slim
h2 = t('.loads dates')
ul
  - @dates.each do |date|
    li
      = link_to "#{date}", loads_path(date: date)